### PR TITLE
Infinite scrolling on tabs and js refactoring

### PR DESCRIPTION
**Pull request by WojtekReu**
I decreased code 57 lines less. I Hope service would be faster.

### CODE REVIEW

**Comment by ppeczek** [comment]
Great! I will read through your commit in the evening. Hope you
successfully debuged tab problem, didn’t you?
24 wrz 2016 22:16 "Wojciech Zając" <notifications@github.com> napisał(a):

**Comment by WojtekReu** [comment]
Yes, tabs and infinite scrolling on user profile working well. I didn't touch events. Still there is old separated function doing infinite scrolling. Ranking page do not have infinite scrolling yet.

**Comment by ppeczek** [comment]
I thought I didn’t remove infinite scroll from ranking in this PR
25 wrz 2016 17:22 "Wojciech Zając" <notifications@github.com> napisał(a):

**Comment by WojtekReu** [comment]
There was no infinite scrolling on ranking page.

**Pull request merged**
